services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  rag-server:
    build:
      context: .
      args:
        CUDA_VARIANT: ${CUDA_VARIANT:-cu118}
    container_name: rag_manager
    depends_on:
      - qdrant
    volumes:
      - .:/app
      - ./DOKUMENTY:/app/DOKUMENTY
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_HOST=qdrant
    stdin_open: true
    tty: true

volumes:
  qdrant_data:
